### R Lists Basics

WE've covered Vectors, Matrices.and Data frames. now we will learn about our last basic bulit -in data structure: the list.

List will allow us to sotre a variety of data structures under a single variable. This means we coudld store a vector, matrix dataframe, etc undera silgle list for example:

In [9]:
# create avector
v <- c(1,2,3,4,5)
# create a mitrix
m <- matrix(1:10,nrow=2)
#Create a data frame
df <- women

In [11]:
v

[1] 1 2 3 4 5

In [14]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [16]:
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

### Using list()

In [19]:
li  <- list(v,m,df)

In [21]:
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

You will notice that the list() assigned numbers to each of the ojects in the list ,but we can also addign names in the folowing manner:

In [27]:
li  <- list(sample_vec =v, sample_mat =m, sample_df = df)

In [30]:
#ignore the "error in vapply", this won't occur in Rstudio!
li

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

#### Selecting ibjects from a list 

You can use bracket notation to show objects ina list and double brackets to actually grab the objects form the list for ecample:

In [36]:
# Single brackets 
li[1] # by index

$sample_vec
[1] 1 2 3 4 5

In [39]:
# By name 
li['sample_vec']

$sample_vec
[1] 1 2 3 4 5

In [40]:
#notice the type!
class(li['smaple_vec'])

[1] "list"

In [41]:
#Use double brackets toactually grab the items
li[['sample_vec']]

[1] 1 2 3 4 5

In [43]:
#Can also use $ notation 
li$sample_vec

[1] 1 2 3 4 5

You cna also index on top of this once you've selected the objects form the list for exampl:

In [48]:
li[['sample_vec']][1]

[1] 1

In [50]:
li[['sample_mat']]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [52]:
li[['sample_mat']][1:2,1:2]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [56]:
li[['sample_df']]['height']

height
1  58    
2  59    
3  60    
4  61    
5  62    
6  63    
7  64    
8  65    
9  66    
10 67    
11 68    
12 69    
13 70    
14 71    
15 72

### Combining lists

lists can hold others list You can also combine its using the cimbine function c():

In [61]:
double_list  <- c(li,li)

In [62]:
double_list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [64]:
str(double_list)

List of 6
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...


### Creating Matrix

We've learned about vectors which allow us to store indexed elements. A matrix will allow us to have a 2-dimensional data structure which contains elements consisting of the same data type.<br>

Before we talk about the Matrix, we should show a quick tip for quickly creating sequential numeric vectors, you can use the colon notation from slicing to create sequential vectors:

In [82]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
v  <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

Great.Now,to create a matrix in R, you use the matrix() function. We can pass

In [6]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

Notice how the output is displayed. Here we have a two-dimensional matrix which is 10 rows by 1 column. Now what if we want to specify the number of rows? We can pass the parameter/argument into the matrix function called nrow which stands for number of rows:

In [8]:
matrix(v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Now we have a 2 by 5 matrix. Notice that the nrow argument allows this to happen. But how do we decide the fill order? We could have filed columns first (as we did above) or filled out the rows first insequential order. The byrow argument allows you to specify whether or not you want to fill out the matrix by rows or by columns. For example:

In [10]:
matrix(1:12,byrow = FALSE,nrow = 4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [11]:
matrix(1:12,byrow = TRUE , nrow = 4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [12]:
v

[1]  1  2  3  4  5  6  7  8  9 10

### Creating Mattices from Vectors

We can combine vectors to later input them into a matrix. For example imagine the following vectors below of stock prices:

In [47]:
#not real prices 
goog  <- c(450,451,452,445,468)
msft  <- c(230,231,232,236,228)

In [48]:
stocks  <- c(goog,msft)

In [49]:
stock.matrix  <- matrix(stocks,byrow= TRUE,nrow =2)

In [50]:
stock.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

### Naming Matices

Now that we have our matrix, it would be nice to name the rows and columns for reference. We can do this similarly to the names() function for vectors, but in this case we define colnames() and rownames(). So let's name our stock matrix:

In [51]:
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names  <- c('GOOG',"MSFT")

In [56]:
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

In [57]:
stock.matrix

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

Looking good! Now we are starting to really build up something powerful here, you should begin to be reminded of a spreadsheet!<br>

That's is for the basics of creating a matrix! In the next lecture we will be building off this matrix of stock prices, so keep the code for future reference!

### Factor and catagorical Matrices 

In this lecture we will discuss the factor() function and its use for creating categorical matrices. This specific function will become extremely useful when we begin to apply data analysis and machine learning techniques to our data, this idea is sometimes also known as creating dummy variables.<br>

Let's start by showing an example of why and how we build this matrix. Imagine we have the following vectors representing data from an animal sanctuary for dogs ('d') and cats ('c') where they each have a corresponding id number in another vector.

In [62]:
animal  <- c('d','c','d','c','c')
id  <- c(1,2,3,4,5)

We want to convert the animal vector into information that an algorithm or equation can understand more easily. Meaning we want to begin to check how many categories (factor levels) are in our character vector.<br>

We can pass the vector through the factor() function like so to get this information:

In [66]:
factor.ani  <- factor(animal)

In [68]:
#Will show levels aas well on Rstudio or R Console
factor.ani

[1] d c d c c
Levels: c d

We can see that we have two levels, 'd' and 'c'. In R there are two distinct types of categorical variables, a ordinal categorical variable and a nominal categorical variable .<br>

Nominal categorical variables don't have any order, such as dogs and cats (there is no order to them). Versus Ordinal categorical variables (as the name implies) do have an order. For example, if you had the vector:

In [71]:
ord.cat <- c('cold','med','hot')

You could begin to assign in order to these variables, such as:<br>

cold < med < hot<br>

if you wanted to assign an order while using the factor() function, you can pass in the arguments ordered=True and the pass in the levels= and pass in a vector in the order you want the levels to be in. So for example:

In [78]:
temps  <- c('cold','med','cold','med','hot','hot','cold')
fact.temp  <- factor(temps,ordered = TRUE , levels = c('cold','med','hot'))
fact.temp

[1] cold med  cold med  hot  hot  cold
Levels: cold < med < hot

This information is useful when used along with the summary() function which is an amazingly convenient function for quickly getting information from a matrix or vector. For example:

In [79]:
summary(temps)

   Length     Class      Mode 
        7 character character 

In [80]:
summary(fact.temp)

cold  med  hot 
   3    2    2

Later on we will revisit this idea of using the factor() function and ordered argument. For now that is all we need to know.

### Matrix Arithemetic

We can perform element by element mathematical operations on a matrix with a scalar (single number) just like we could with vectors. Let's see some quick examples:

In [83]:
mat  <- matrix(1:50,byrow = TRUE,nrow= 5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [84]:
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [85]:
1/mat

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
[2,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.06250000
[3,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000 0.03846154
[4,] 0.03225806 0.03125000 0.03030303 0.02941176 0.02857143 0.02777778
[5,] 0.02439024 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913
     [,7]       [,8]       [,9]       [,10]     
[1,] 0.14285714 0.12500000 0.11111111 0.10000000
[2,] 0.05882353 0.05555556 0.05263158 0.05000000
[3,] 0.03703704 0.03571429 0.03448276 0.03333333
[4,] 0.02702703 0.02631579 0.02564103 0.02500000
[5,] 0.02127660 0.02083333 0.02040816 0.02000000

In [86]:
mat/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20   
[5,] 20.5 21   21.5 22   22.5 23   23.5 24   24.5 25

In [87]:
mat^2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

### Comparision operators with matieces 

We can similarly perform comparison operations across an entire matrix to return a matrix of logicals:

In [90]:
mat > 17

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

### Matrix Arithemetic with multiple matrices


We an use multiple with arithemetic as well,for example:


In [94]:
mat + mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [95]:
mat/mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [96]:
mat ^ mat

[,1]         [,2]         [,3]         [,4]         [,5]        
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[3,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34
[4,] 1.706917e+46 1.461502e+48 1.291100e+50 1.175664e+52 1.102507e+54
[5,] 1.330878e+66 1.501309e+68 1.734377e+70 2.050774e+72 2.480636e+74
     [,6]         [,7]         [,8]         [,9]         [,10]       
[1,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[2,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[3,] 6.156120e+36 4.434265e+38 3.314552e+40 2.567686e+42 2.058911e+44
[4,] 1.063874e+56 1.055513e+58 1.075912e+60 1.125951e+62 1.208926e+64
[5,] 3.068035e+76 3.877924e+78 5.007021e+80 6.600972e+82 8.881784e+84

### Matrix multiplication 

A quick side note on matrix multiplications. You can perform arithmetic multiplication on an element by element basis using the * sign in R. You should note this is not the same as Matrix Multiplication. If you are familiar with the mathematics behind this topic and want to use R to perform true matrix multiplication, you can use the following:

In [100]:
mat2  <- matrix(1:9,nrow =3)

In [101]:
mat2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [105]:
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

Okay, that's it for matrices! Later on we will learn how to use factor() to quickly create categoical matrices from character elements.

### Matrix Operations

Now that we've learned how to create a matrix, let's learn how to use functions and perform operations on it!

Run the following code to create the stock.matrix from earlier

In [112]:
# Prices
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

# Put vectors into matrix
stocks <- c(goog,msft)
stock.matrix <- matrix(stocks,byrow=TRUE,nrow=2)

# Name matrix
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names <- c('GOOG','MSFT')
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

# Display
stock.matrix

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

In [116]:
colSums(stock.matrix)

Mon Tue Wed Thu Fri 
680 682 684 681 696

In [117]:
# Doesn't really make sense for stocks, but just to show how it works
rowSums(stock.matrix)


GOOG MSFT 
2266 1157

We can also do other mathematical operations, check this reference for all functions available.

In [120]:
rowMeans(stock.matrix)

GOOG  MSFT 
453.2 231.4

### Binding columns and rows

 Let's go ahead and see how we can add columns and rows to a matrix, we can use the cbind() to bind a new column, and rbind() to bind a new row. For example, let's bind a new row with Facebook stock:

In [123]:
FB <- c(111,112,113,120,145)

In [125]:
tech.stocks  <- rbind(stock.matrix,FB)

In [126]:
tech.stocks

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228
FB   111 112 113 120 145

Now lets add an average column to the matrix:

In [128]:
avg  <- rowMeans(tech.stocks)

In [129]:
avg

GOOG  MSFT    FB 
453.2 231.4 120.2

In [130]:
tech.stocks  <- cbind(tech.stocks,avg)

In [131]:
tech.stocks

Mon Tue Wed Thu Fri avg  
GOOG 450 451 452 445 468 453.2
MSFT 230 231 232 236 228 231.4
FB   111 112 113 120 145 120.2

Great! We've gone over some basic matrix operations! Up next we will talk about selecting and indexing matrix elements!

## Matrix Selection and Indexing 

Just like with vectors, we use the square bracket notation to select elements from a matrix. Since we have two dimensions to work with, we'll use a comma to separate our indexing for each dimension.

So the syntax is then:

example.matrix[rows,columns]

where the index notation (e.g. 1:5) is put in place of the rows or columns . If either rows or columns is left blank, then we are selecting all the rows and columns.

Let's work through some examples:

In [138]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)

In [139]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [140]:
#grab first row
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [141]:
#grab first column
mat[,1]

[1]  1 11 21 31 41

In [142]:
#Grab first 3 rows
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [144]:
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [145]:
#Grab last two columns 
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [146]:
# Grab a center square of:
# 15,16
# 25,26
mat[2:3,5:6]

[,1] [,2]
[1,] 15   16  
[2,] 25   26

Great job! You should practice this! Just pick out blocks from the matrix and see if you can successfully index them. Up next we will learn about Matrix Arithmetic!

## DataFrame Basics 

We've learned about vectors and their two-dimensional counterpart, matrices. Now we will learn about Dataframes, one of the main tools for data analysis with R! Matrix inputs were limited because all the data inside of the matrix had to be of the same data type (numerics, logicals, etc). With Dataframes we will be able to organize and mix data types to create a very powerful data structure tool!

R actually has built in DataFrames for quick reference to play around with! Check out the following dataframes that are built-in!

In [153]:
#Date frame 
state.x77

Population Income Illiteracy Life Exp Murder HS Grad Frost
Alabama         3615      3624   2.1        69.05    15.1   41.3     20  
Alaska           365      6315   1.5        69.31    11.3   66.7    152  
Arizona         2212      4530   1.8        70.55     7.8   58.1     15  
Arkansas        2110      3378   1.9        70.66    10.1   39.9     65  
California     21198      5114   1.1        71.71    10.3   62.6     20  
Colorado        2541      4884   0.7        72.06     6.8   63.9    166  
Connecticut     3100      5348   1.1        72.48     3.1   56.0    139  
Delaware         579      4809   0.9        70.06     6.2   54.6    103  
Florida         8277      4815   1.3        70.66    10.7   52.6     11  
Georgia         4931      4091   2.0        68.54    13.9   40.6     60  
Hawaii           868      4963   1.9        73.60     6.2   61.9      0  
Idaho            813      4119   0.6        71.87     5.3   59.5    126  
Illinois       11197      5107   0.9        70.14    10.3   52.6    127  
Indiana         5313      4458   0.7        70.88     7.1   52.9    122  
Iowa            2861      4628   0.5        72.56     2.3   59.0    140  
Kansas          2280      4669   0.6        72.58     4.5   59.9    114  
Kentucky        3387      3712   1.6        70.10    10.6   38.5     95  
Louisiana       3806      3545   2.8        68.76    13.2   42.2     12  
Maine           1058      3694   0.7        70.39     2.7   54.7    161  
Maryland        4122      5299   0.9        70.22     8.5   52.3    101  
Massachusetts   5814      4755   1.1        71.83     3.3   58.5    103  
Michigan        9111      4751   0.9        70.63    11.1   52.8    125  
Minnesota       3921      4675   0.6        72.96     2.3   57.6    160  
Mississippi     2341      3098   2.4        68.09    12.5   41.0     50  
Missouri        4767      4254   0.8        70.69     9.3   48.8    108  
Montana          746      4347   0.6        70.56     5.0   59.2    155  
Nebraska        1544      4508   0.6        72.60     2.9   59.3    139  
Nevada           590      5149   0.5        69.03    11.5   65.2    188  
New Hampshire    812      4281   0.7        71.23     3.3   57.6    174  
New Jersey      7333      5237   1.1        70.93     5.2   52.5    115  
New Mexico      1144      3601   2.2        70.32     9.7   55.2    120  
New York       18076      4903   1.4        70.55    10.9   52.7     82  
North Carolina  5441      3875   1.8        69.21    11.1   38.5     80  
North Dakota     637      5087   0.8        72.78     1.4   50.3    186  
Ohio           10735      4561   0.8        70.82     7.4   53.2    124  
Oklahoma        2715      3983   1.1        71.42     6.4   51.6     82  
Oregon          2284      4660   0.6        72.13     4.2   60.0     44  
Pennsylvania   11860      4449   1.0        70.43     6.1   50.2    126  
Rhode Island     931      4558   1.3        71.90     2.4   46.4    127  
South Carolina  2816      3635   2.3        67.96    11.6   37.8     65  
South Dakota     681      4167   0.5        72.08     1.7   53.3    172  
Tennessee       4173      3821   1.7        70.11    11.0   41.8     70  
Texas          12237      4188   2.2        70.90    12.2   47.4     35  
Utah            1203      4022   0.6        72.90     4.5   67.3    137  
Vermont          472      3907   0.6        71.64     5.5   57.1    168  
Virginia        4981      4701   1.4        70.08     9.5   47.8     85  
Washington      3559      4864   0.6        71.72     4.3   63.5     32  
West Virginia   1799      3617   1.4        69.48     6.7   41.6    100  
Wisconsin       4589      4468   0.7        72.48     3.0   54.5    149  
Wyoming          376      4566   0.6        70.29     6.9   62.9    173  
               Area  
Alabama         50708
Alaska         566432
Arizona        113417
Arkansas        51945
California     156361
Colorado       103766
Connecticut      4862
Delaware         1982
Florida         54090
Georgia         58073

In [154]:
# us personal expenses
USPersonalExpenditure

1940   1945   1950  1955 1960 
Food and Tobacco    22.200 44.500 59.60 73.2 86.80
Household Operation 10.500 15.500 29.00 36.5 46.20
Medical and Health   3.530  5.760  9.71 14.0 21.10
Personal Care        1.040  1.980  2.45  3.4  5.40
Private Education    0.341  0.974  1.80  2.6  3.64

In [155]:
#women
women

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

## Working With DataFrames

You'll notice the states dataframe was really big, we can use the head() and tail() functions to view the first and last 6 rows respectively. Let's take a look:

In [160]:
#Quick variables assignment to save typing 
states  <- state.x77

In [161]:
head(states)

Population Income Illiteracy Life Exp Murder HS Grad Frost Area  
Alabama     3615      3624   2.1        69.05    15.1   41.3     20    50708
Alaska       365      6315   1.5        69.31    11.3   66.7    152   566432
Arizona     2212      4530   1.8        70.55     7.8   58.1     15   113417
Arkansas    2110      3378   1.9        70.66    10.1   39.9     65    51945
California 21198      5114   1.1        71.71    10.3   62.6     20   156361
Colorado    2541      4884   0.7        72.06     6.8   63.9    166   103766

In [162]:
tail(states)

Population Income Illiteracy Life Exp Murder HS Grad Frost Area 
Vermont        472       3907   0.6        71.64    5.5    57.1    168    9267
Virginia      4981       4701   1.4        70.08    9.5    47.8     85   39780
Washington    3559       4864   0.6        71.72    4.3    63.5     32   66570
West Virginia 1799       3617   1.4        69.48    6.7    41.6    100   24070
Wisconsin     4589       4468   0.7        72.48    3.0    54.5    149   54464
Wyoming        376       4566   0.6        70.29    6.9    62.9    173   97203

### DataFrame Overview of information

We can use the str() to get the structure of a dataframe, which gives information on the structure of the dataframe and the data it contains, such as variable names and data types. We can use summary() to get a quick statistical summary of all the columns of a DataFrame, depending on the data, this may or may not be useful!

In [165]:
#stastical summary of data 
summary(states)

   Population        Income       Illiteracy       Life Exp    
 Min.   :  365   Min.   :3098   Min.   :0.500   Min.   :67.96  
 1st Qu.: 1080   1st Qu.:3993   1st Qu.:0.625   1st Qu.:70.12  
 Median : 2838   Median :4519   Median :0.950   Median :70.67  
 Mean   : 4246   Mean   :4436   Mean   :1.170   Mean   :70.88  
 3rd Qu.: 4968   3rd Qu.:4814   3rd Qu.:1.575   3rd Qu.:71.89  
 Max.   :21198   Max.   :6315   Max.   :2.800   Max.   :73.60  
     Murder          HS Grad          Frost             Area       
 Min.   : 1.400   Min.   :37.80   Min.   :  0.00   Min.   :  1049  
 1st Qu.: 4.350   1st Qu.:48.05   1st Qu.: 66.25   1st Qu.: 36985  
 Median : 6.850   Median :53.25   Median :114.50   Median : 54277  
 Mean   : 7.378   Mean   :53.11   Mean   :104.46   Mean   : 70736  
 3rd Qu.:10.675   3rd Qu.:59.15   3rd Qu.:139.75   3rd Qu.: 81163  
 Max.   :15.100   Max.   :67.30   Max.   :188.00   Max.   :566432  

In [166]:
#structure of data
str(states)

 num [1:50, 1:8] 3615 365 2212 2110 21198 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
  ..$ : chr [1:8] "Population" "Income" "Illiteracy" "Life Exp" ...


### Creating Data frames

A quick note some people write Dataframe as one word, but in R its more commonly written as two words: data frame. Not a very huge deal either way, but if someone writes DataFrame they may be referring to a Python/pandas DataFrame, so keep that in mind!

We can create data frames using the data.frame() function and pass vectors as arguments, which will then convert the vectors into columns of the data frame. Let's see a simple example:

In [170]:
# some made up weather data 
days <- c('mon','tue','wed','thu','fri')
temp <- c(22.2,21,23,24,25)
rain <- c(TRUE,TRUE,FALSE,FALSE,TRUE) 

In [171]:
#Pass in the vectors:
df  <- data.frame(days,temp,rain)

In [172]:
df

days temp rain 
1 mon  22.2  TRUE
2 tue  21.0  TRUE
3 wed  23.0 FALSE
4 thu  24.0 FALSE
5 fri  25.0  TRUE

In [173]:
#str
str(df)

'data.frame':	5 obs. of  3 variables:
 $ days: Factor w/ 5 levels "fri","mon","thu",..: 2 4 5 3 1
 $ temp: num  22.2 21 23 24 25
 $ rain: logi  TRUE TRUE FALSE FALSE TRUE


In [174]:
summary(df)

  days        temp          rain        
 fri:1   Min.   :21.00   Mode :logical  
 mon:1   1st Qu.:22.20   FALSE:2        
 thu:1   Median :23.00   TRUE :3        
 tue:1   Mean   :23.04                  
 wed:1   3rd Qu.:24.00                  
         Max.   :25.00                  

That's it for the basics, up next we will learn about selection and indexing Data Frame elements!