### R Lists Basics

WE've covered Vectors, Matrices.and Data frames. now we will learn about our last basic bulit -in data structure: the list.

List will allow us to sotre a variety of data structures under a single variable. This means we coudld store a vector, matrix dataframe, etc undera silgle list for example:

In [9]:
# create avector
v <- c(1,2,3,4,5)
# create a mitrix
m <- matrix(1:10,nrow=2)
#Create a data frame
df <- women

In [11]:
v

[1] 1 2 3 4 5

In [14]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [16]:
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

### Using list()

In [19]:
li  <- list(v,m,df)

In [21]:
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

You will notice that the list() assigned numbers to each of the ojects in the list ,but we can also addign names in the folowing manner:

In [27]:
li  <- list(sample_vec =v, sample_mat =m, sample_df = df)

In [30]:
#ignore the "error in vapply", this won't occur in Rstudio!
li

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

#### Selecting ibjects from a list 

You can use bracket notation to show objects ina list and double brackets to actually grab the objects form the list for ecample:

In [36]:
# Single brackets 
li[1] # by index

$sample_vec
[1] 1 2 3 4 5

In [39]:
# By name 
li['sample_vec']

$sample_vec
[1] 1 2 3 4 5

In [40]:
#notice the type!
class(li['smaple_vec'])

[1] "list"

In [41]:
#Use double brackets toactually grab the items
li[['sample_vec']]

[1] 1 2 3 4 5

In [43]:
#Can also use $ notation 
li$sample_vec

[1] 1 2 3 4 5

You cna also index on top of this once you've selected the objects form the list for exampl:

In [48]:
li[['sample_vec']][1]

[1] 1

In [50]:
li[['sample_mat']]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [52]:
li[['sample_mat']][1:2,1:2]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [56]:
li[['sample_df']]['height']

height
1  58    
2  59    
3  60    
4  61    
5  62    
6  63    
7  64    
8  65    
9  66    
10 67    
11 68    
12 69    
13 70    
14 71    
15 72

### Combining lists

lists can hold others list You can also combine its using the cimbine function c():

In [61]:
double_list  <- c(li,li)

In [62]:
double_list

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$sample_vec
[1] 1 2 3 4 5

$sample_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$sample_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [64]:
str(double_list)

List of 6
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ sample_vec: num [1:5] 1 2 3 4 5
 $ sample_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ sample_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...


### Creating Matrix

We've learned about vectors which allow us to store indexed elements. A matrix will allow us to have a 2-dimensional data structure which contains elements consisting of the same data type.<br>

Before we talk about the Matrix, we should show a quick tip for quickly creating sequential numeric vectors, you can use the colon notation from slicing to create sequential vectors:

In [82]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
v  <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

Great.Now,to create a matrix in R, you use the matrix() function. We can pass

In [6]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

Notice how the output is displayed. Here we have a two-dimensional matrix which is 10 rows by 1 column. Now what if we want to specify the number of rows? We can pass the parameter/argument into the matrix function called nrow which stands for number of rows:

In [8]:
matrix(v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Now we have a 2 by 5 matrix. Notice that the nrow argument allows this to happen. But how do we decide the fill order? We could have filed columns first (as we did above) or filled out the rows first insequential order. The byrow argument allows you to specify whether or not you want to fill out the matrix by rows or by columns. For example:

In [10]:
matrix(1:12,byrow = FALSE,nrow = 4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [11]:
matrix(1:12,byrow = TRUE , nrow = 4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [12]:
v

[1]  1  2  3  4  5  6  7  8  9 10

### Creating Mattices from Vectors

We can combine vectors to later input them into a matrix. For example imagine the following vectors below of stock prices:

In [47]:
#not real prices 
goog  <- c(450,451,452,445,468)
msft  <- c(230,231,232,236,228)

In [48]:
stocks  <- c(goog,msft)

In [49]:
stock.matrix  <- matrix(stocks,byrow= TRUE,nrow =2)

In [50]:
stock.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

### Naming Matices

Now that we have our matrix, it would be nice to name the rows and columns for reference. We can do this similarly to the names() function for vectors, but in this case we define colnames() and rownames(). So let's name our stock matrix:

In [51]:
days <- c('Mon','Tue','Wed','Thu','Fri')
st.names  <- c('GOOG',"MSFT")

In [56]:
colnames(stock.matrix) <- days
rownames(stock.matrix) <- st.names

In [57]:
stock.matrix

Mon Tue Wed Thu Fri
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

Looking good! Now we are starting to really build up something powerful here, you should begin to be reminded of a spreadsheet!<br>

That's is for the basics of creating a matrix! In the next lecture we will be building off this matrix of stock prices, so keep the code for future reference!

In [ ]:
Factor and catagorical Matrices 