# Ensemble methods iris data 

In [1]:
import pandas as pd
import numpy as np

In [2]:
import sklearn.datasets as datasets

In [29]:
#loading and splitting data features and target
X, y = datasets.load_iris(return_X_y=True)

### X is features , y is target variable But we are not using sccalling here 

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
scaler = StandardScaler()

In [6]:
scaler.fit(X,y)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
scaled_features = scaler.fit_transform(X,y)

In [37]:
scaled_features

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

# Train Test Split

In [18]:
from sklearn.model_selection import train_test_split


In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2 )

# Bagging Classifier

In [24]:
from sklearn.ensemble import BaggingClassifier # imported bagging classifier algorithm 
BaggingClassifier?

In [26]:
from sklearn.neighbors import KNeighborsClassifier
m = KNeighborsClassifier(n_neighbors=3)

In [27]:
# lets make a bagging classifier
bag = BaggingClassifier(
    m, 
    max_samples=.5, 
    max_features=2, 
    n_jobs=2,
    oob_score=True)

In [28]:
bag.fit(X_train, y_train) # 

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto',
                                                      leaf_size=30,
                                                      metric='minkowski',
                                                      metric_params=None,
                                                      n_jobs=None,
                                                      n_neighbors=3, p=2,
                                                      weights='uniform'),
                  bootstrap=True, bootstrap_features=False, max_features=2,
                  max_samples=0.5, n_estimators=10, n_jobs=2, oob_score=True,
                  random_state=None, verbose=0, warm_start=False)

# Predictions and Evaluations of Bagging 

In [30]:
pred = bag.predict(X_test)

In [31]:
from sklearn.metrics import classification_report,confusion_matrix

In [32]:
print(confusion_matrix(y_test,pred))

[[10  0  0]
 [ 0 10  1]
 [ 0  0  9]]


In [33]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.91      0.95        11
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [34]:
bag.oob_score_

0.9583333333333334

In [35]:
bag.score(X, y)

0.9666666666666667

# Descision  Tree classifier

In [43]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier?

In [44]:
Ds = DecisionTreeClassifier()

In [45]:
Ds.fit(X,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

# Predictions and Evaluations of Descision Tree classifer

In [46]:
pred1 = Ds.predict(X_test) 

In [49]:
print(confusion_matrix(y_test,pred1))

[[11  0  0]
 [ 0 11  0]
 [ 0  0  8]]


In [50]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [53]:
Ds.score(X,y)

1.0

# Random Forests

In [54]:
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifier?

In [55]:
Rm = RandomForestClassifier(n_estimators=20, oob_score=True)

In [56]:
Rm.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

# Predictions and Evaluations of Random classifer

In [57]:
pred2 = Rm.predict(X_test) 

In [59]:
print(confusion_matrix(y_test,pred2))

[[11  0  0]
 [ 0 11  0]
 [ 0  0  8]]


In [60]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [61]:
Rm.score(X, y)

1.0

# AdaBoost Classifier 

In [62]:
from sklearn.ensemble import AdaBoostClassifier
AdaBoostClassifier?

In [63]:
Ad = AdaBoostClassifier(base_estimator=None, n_estimators=100)

In [64]:
Ad.fit(X, y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=None)

# Predictions and Evaluations of AdABoost classifer

In [66]:
pred3 = Ad.predict(X_test) 

In [68]:
print(confusion_matrix(y_test,pred3))

[[11  0  0]
 [ 0  9  2]
 [ 0  0  8]]


In [69]:
print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.82      0.90        11
           2       0.80      1.00      0.89         8

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30



In [65]:
Ad.score(X, y)

0.9733333333333334

# Gradient Tree Boosting

In [70]:
from sklearn.ensemble import GradientBoostingClassifier
GradientBoostingClassifier?

In [71]:
Gb = GradientBoostingClassifier(n_estimators=10)

Gb.fit(X, y)

Gb.score(X, y)

0.9933333333333333

# Predictions and Evaluations of Gradient Tree Boosting 

In [72]:
pred4 = Gb.predict(X_test) 

In [74]:
print(confusion_matrix(y_test,pred4))

[[11  0  0]
 [ 0 11  0]
 [ 0  0  8]]


In [75]:
print(classification_report(y_test,pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [76]:
Gb.score(X, y)

0.9933333333333333

# Voting Classifier

In [77]:
from sklearn.ensemble import VotingClassifier
VotingClassifier?

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier


Vm = VotingClassifier(
    estimators=[('lr', LogisticRegression()), 
                ('rf', RandomForestClassifier()), 
                ('gnb', GaussianNB())], voting='hard')

In [90]:
Vm.fit(X, y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     ccp_alpha=0.0,
                                                     class_weight=None,
                                             

In [91]:
Vm.score(X, y)

0.98